swagger: "2.0"
info:
  description: "."
  version: "0.1.0"
  title: "Fusion Creator API"
basePath: "/v1"
schemes:
- "http"
- "https"
paths:
  /service:
    get:
      tags:
      - "service"
      summary: "Retrieve the list of services with theiur description"
      description: "Should include "
      operationId: "listService"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
    
  /application:
    get:
      tags:
      - "application"
      summary: "Retrieve the deployed applications"
      description: "Should include "
      operationId: "listApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
    post:
      tags:
      - "application"
      summary: "Create an application"
      description: "Should include "
      operationId: "createApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
  /application/{appId}:
    get:
      tags:
      - "application"
      summary: "get an application"
      description: ""
      operationId: "getApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
          
    put:
      tags:
      - "application"
      summary: "Update an application"
      description: ""
      operationId: "updateApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
    delete:
      tags:
      - "application"
      summary: "Delete an application"
      description: ""
      operationId: "deleteApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
  /application/{appId}/status:
    get:
      tags:
      - "application"
      summary: "get an application"
      description: ""
      operationId: "getAppStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
  /application/{appId}/service:
    post:
      tags:
      - "application"
      summary: "Add a service"
      description: ""
      operationId: "addServiceApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
    get:
      tags:
      - "application"
      summary: "get the services of an Application"
      description: ""
      operationId: "getAppServices"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
  /application/{appId}/service/{serviceId}:
    delete:
      tags:
      - "application"
      summary: "Delete a service of an application"
      description: ""
      operationId: "deleteAppService"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
        - in: path
          name: serviceId
          type: string
          required: true
          description: ID of the app to update
  /application/{appId}/service/{serviceId}/status:
    get:
      tags:
      - "application"
      summary: "Get the deployment status of a service of an application"
      description: ""
      operationId: "getAppServiceStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
      parameters:
        - in: path
          name: appId
          type: string
          required: true
          description: ID of the app to update
        - in: path
          name: serviceId
          type: string
          required: true
          description: ID of the app to update  
  
          
      
    
     
definitions:
  Application:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "Trainer Trading"
      service:
        type: "array"
        items:
          $ref: '#/definitions/Service'

     

    
  Service:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "ffdc/reporting"
        description: "The name of the service (required)"
      version:
        type: "string"
        example: "0.1.0"
        description: "A SemVer 2 version"
      description:
        type: "string"
        example: "The service create a report back server."
        description: "A single-sentence description of this service"
      keywords:
        type: "array"
        items:
          type: "string"
        example: "[front,transient,...]"
      home:
        type: "string"
        example: "http://k8s.io"
      icon:
        type: "string"
        example: "http://k8s.io/logo.png"
      deprecated:
        type: "boolean"
        example: "false"
      externalLinkName:
        type: "string"
        example: "reporting"
        description: "Name of the service deployed "
      
  

        

