@startuml

' color to use
' #FFB05A
' #FFB05A
' #D5E821
' #31FFB4
' #514BEF
skinparam handwritten true

skinparam interface {
  backgroundColor RosyBrown
  borderColor orange
}

skinparam class {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
    BackgroundColor<<Apache>> Red
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BackgroundColor <<Blue>> DeepSkyBlue
    BorderColor black
    BackgroundColor gold
    ArrowFontName Impact
    ArrowColor #996655
    ArrowFontColor #777777

}

header
<font color=red>Warning:</font>
Draft
endheader
center footer Tenant,User,Workspace,Application and Component


package "System" <<Namespace>>#DDFFDD {
  object Workspace <<CustomResourceDefinition>>{
    String tenant
    String namespace
    String user
    Application []applications
  }
  object Application <<CustomResourceDefinition>>{
      String name
      String namespace
      Component components[]
    }
  object Component <<CustomResourceDefinition>>{
      String name
      String namespace
      String helmname
      String version
  }
  Workspace *-- Application
  Application *-- Component
}






@enduml