kind: KApplication
apiVersion: kulbe.enablecloud.github.com/v1
metadata:
  name: sample1
spec:
  components:
    items:
      - spec:
         helmname: "stable/consul"
      - metadata:
          name: consul2
        spec:
         helmname: "stable/consul"
      - metadata:
          name: consul3
        spec:
         helmname: "stable/consul"
